### ISSUE TITLE
Practica 1 de Realidad Aumentada

### ISSUE THREAD

**Issue by AxayacatlS** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-AxayacatlS#2]
Análisis de 2 aplicaciones AR y VR

[Practica 1 Aplicaciones Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-AxayacatlS/files/6133964/Practica.1.Aplicaciones.Realidad.Aumentada.pdf)

**Comment by ObedG** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
